"""empty message

Revision ID: 8269c75d6837
Revises: 9d916f14d306
Create Date: 2023-05-20 12:07:03.219121+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8269c75d6837'
down_revision = '9d916f14d306'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('short_url_prefix', sa.String(), server_default='/urls/r', nullable=False))
    op.add_column('urls', sa.Column('short_url_path', sa.String(), nullable=True))
    op.drop_index('ix_urls_short_url', table_name='urls')
    op.create_index(op.f('ix_urls_short_url_path'), 'urls', ['short_url_path'], unique=True)
    op.drop_column('urls', 'short_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_urls_short_url_path'), table_name='urls')
    op.create_index('ix_urls_short_url', 'urls', ['short_url'], unique=False)
    op.drop_column('urls', 'short_url_path')
    op.drop_column('urls', 'short_url_prefix')
    # ### end Alembic commands ###
