services:
  fastapi-backend:
    container_name: urlshortener-backend
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.fastapi.dev
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./src-backend:/app
    depends_on:
      - db
      - adminer

  db:
    image: postgres:15.3-bullseye
    container_name: Postgres
    restart: always
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: Adminer
    restart: always
    ports:
      - 8080:8080